phpCAS: phpCAS Class Reference
phpCAS Class Reference
[User interface]
Public Member Functions
client ($server_version, $server_hostname, $server_port, $server_uri, $start_session=true)
proxy ($server_version, $server_hostname, $server_port, $server_uri, $start_session=true)
setDebug ($filename= '')
backtrace ()
trace ($str)
traceBegin ()
traceEnd ($res= '')
traceExit ()
setLang ($lang)
getVersion ()
setHTMLHeader ($header)
setHTMLFooter ($footer)
setPGTStorageFile ($format= '', $path= '')
setPGTStorageDB ($user, $password, $database_type= '', $hostname= '', $port=0, $database= '', $table= '')
serviceWeb ($url, &$err_code, &$output)
serviceMail ($url, $service, $flags, &$err_code, &$err_msg, &$pt)
setCacheTimesForAuthRecheck ($n)
checkAuthentication ()
forceAuthentication ()
renewAuthentication ()
authenticate ()
isAuthenticated ()
isSessionAuthenticated ()
getUser ()
getAttributes ()
handleLogoutRequests ($check_client=true, $allowed_clients=false)
getServerLoginURL ()
setServerLoginURL ($url= '')
setServerServiceValidateURL ($url= '')
setServerProxyValidateURL ($url= '')
setServerSamlValidateURL ($url= '')
getServerLogoutURL ()
setServerLogoutURL ($url= '')
logout ($params="")
logoutWithRedirectService ($service)
logoutWithUrl ($url)
logoutWithRedirectServiceAndUrl ($service, $url)
setFixedCallbackURL ($url= '')
setFixedServiceURL ($url)
getServiceURL ()
retrievePT ($target_service, &$err_code, &$err_msg)
setCasServerCert ($cert)
setCasServerCACert ($cert)
setNoCasServerValidation ()
setExtraCurlOption ($key, $value)
Private Member Functions
log ($str)
error ($msg)
Detailed Description
The phpCAS class is a simple container for the phpCAS library. It provides CAS authentication for web applications written in PHP.
Author:
Pascal Aubry <pascal.aubry at univ-rennes1.fr>
Examples:
example_custom_urls.php, example_db.php, example_file.php, example_gateway.php, example_html.php, example_lang.php, example_proxy.php, example_proxy2.php, example_session_proxy.php, and example_simple.php.
Definition at line 341 of file CAS.php.
Member Function Documentation
phpCAS::setExtraCurlOption ($ key, $ value)
Change CURL options. CURL is used to connect through HTTPS to CAS server
Parameters:
$key the option key
$value the value to set
Definition at line 1469 of file CAS.php.
References error(), traceBegin(), and traceEnd().