phpCAS: Debugging
Debugging
[Implementation]
Functions
phpCAS::backtrace ()
phpCAS::log ($str)
phpCAS::error ($msg)
phpCAS::trace ($str)
phpCAS::traceBegin ()
phpCAS::traceEnd ($res= '')
phpCAS::traceExit ()
Function Documentation
phpCAS::backtrace () [inherited]
This method is a wrapper for debug_backtrace() that is not available in all PHP versions (>= 4.3.0 only)
Definition at line 507 of file CAS.php.
Referenced by phpCAS::checkAuthentication(), phpCAS::client(), phpCAS::error(), phpCAS::forceAuthentication(), phpCAS::proxy(), phpCAS::trace(), phpCAS::traceBegin(), and phpCAS::traceEnd().
phpCAS::error ($ msg) [private, inherited]
This method is used by interface methods to print an error and where the function was originally called from.
Parameters:
$msg the message to print
Definition at line 544 of file CAS.php.
References phpCAS::backtrace(), phpCAS::trace(), and phpCAS::traceExit().
Referenced by CASClient::CASClient(), phpCAS::checkAuthentication(), phpCAS::client(), phpCAS::forceAuthentication(), CASClient::getAttributes(), phpCAS::getAttributes(), phpCAS::getServerLoginURL(), phpCAS::getServerLogoutURL(), phpCAS::getServiceURL(), PGTStorage::getStorageInfo(), PGTStorage::getStorageType(), CASClient::getUser(), phpCAS::getUser(), CASClient::handleLogoutRequests(), phpCAS::handleLogoutRequests(), PGTStorageDB::init(), phpCAS::logout(), phpCAS::logoutWithRedirectService(), phpCAS::logoutWithRedirectServiceAndUrl(), phpCAS::logoutWithUrl(), PGTStorage::PGTStorage(), PGTStorageFile::PGTStorageFile(), phpCAS::proxy(), PGTStorage::read(), CASClient::readURL(), CASClient::renameSession(), phpCAS::retrievePT(), phpCAS::serviceMail(), phpCAS::serviceWeb(), phpCAS::setCacheTimesForAuthRecheck(), phpCAS::setCasServerCACert(), phpCAS::setCasServerCert(), phpCAS::setDebug(), phpCAS::setExtraCurlOption(), phpCAS::setFixedCallbackURL(), phpCAS::setFixedServiceURL(), phpCAS::setHTMLFooter(), phpCAS::setHTMLHeader(), phpCAS::setLang(), phpCAS::setNoCasServerValidation(), CASClient::setPGTStorageDB(), phpCAS::setPGTStorageDB(), CASClient::setPGTStorageFile(), phpCAS::setPGTStorageFile(), phpCAS::setServerLoginURL(), phpCAS::setServerLogoutURL(), phpCAS::setServerProxyValidateURL(), phpCAS::setServerSamlValidateURL(), phpCAS::setServerServiceValidateURL(), PGTStorage::write(), and PGTStorageFile::write().
phpCAS::log ($ str) [private, inherited]
Logs a string in debug mode.
Parameters:
$str the string to write
Definition at line 523 of file CAS.php.
Referenced by CASClient::handleLogoutRequests(), CASClient::isAuthenticated(), CASClient::logout(), CASClient::redirectToCas(), phpCAS::trace(), phpCAS::traceBegin(), phpCAS::traceEnd(), phpCAS::traceExit(), and CASClient::validatePGT().
phpCAS::trace ($ str) [inherited]
This method is used to log something in debug mode.
Definition at line 569 of file CAS.php.
References phpCAS::backtrace(), and phpCAS::log().
Referenced by CASClient::authError(), CASClient::callback(), CASClient::CASClient(), CASClient::checkAuthentication(), phpCAS::error(), CASClient::forceAuthentication(), phpCAS::forceAuthentication(), CASClient::isAuthenticated(), PGTStorageFile::read(), CASClient::readURL(), CASClient::renameSession(), CASClient::renewAuthentication(), CASClient::retrievePT(), CASClient::serviceWeb(), phpCAS::setDebug(), CASClient::setSessionAttributes(), CASClient::validatePGT(), CASClient::validatePT(), CASClient::validateSA(), CASClient::validateST(), and CASClient::wasPreviouslyAuthenticated().
phpCAS::traceBegin () [inherited]
This method is used to indicate the start of the execution of a function in debug mode.
Definition at line 577 of file CAS.php.
References phpCAS::backtrace(), and phpCAS::log().
Referenced by CASClient::authError(), CASClient::buildSAMLPayload(), CASClient::callback(), CASClient::CASClient(), CASClient::checkAuthentication(), phpCAS::checkAuthentication(), phpCAS::client(), CASClient::forceAuthentication(), phpCAS::forceAuthentication(), PGTStorageFile::getPGTIouFilename(), CASClient::getServerLoginURL(), CASClient::getServerSamlValidateURL(), CASClient::handleLogoutRequests(), PGTStorageFile::init(), PGTStorageDB::init(), CASClient::isAuthenticated(), CASClient::logout(), phpCAS::logout(), phpCAS::logoutWithRedirectService(), phpCAS::logoutWithRedirectServiceAndUrl(), phpCAS::logoutWithUrl(), PGTStorage::PGTStorage(), PGTStorageDB::PGTStorageDB(), PGTStorageFile::PGTStorageFile(), phpCAS::proxy(), PGTStorageFile::read(), CASClient::readURL(), CASClient::redirectToCas(), CASClient::renameSession(), CASClient::renewAuthentication(), CASClient::retrievePT(), phpCAS::serviceMail(), CASClient::serviceWeb(), phpCAS::serviceWeb(), phpCAS::setCasServerCACert(), phpCAS::setCasServerCert(), phpCAS::setExtraCurlOption(), phpCAS::setFixedCallbackURL(), phpCAS::setFixedServiceURL(), phpCAS::setNoCasServerValidation(), phpCAS::setPGTStorageDB(), phpCAS::setPGTStorageFile(), phpCAS::setServerLoginURL(), phpCAS::setServerLogoutURL(), phpCAS::setServerProxyValidateURL(), phpCAS::setServerSamlValidateURL(), phpCAS::setServerServiceValidateURL(), CASClient::setSessionAttributes(), CASClient::validatePT(), CASClient::validateSA(), CASClient::validateST(), CASClient::wasPreviouslyAuthenticated(), and PGTStorageFile::write().
phpCAS::traceEnd ($ res = '') [inherited]
This method is used to indicate the end of the execution of a function in debug mode.
Parameters:
$res the result of the function
Definition at line 604 of file CAS.php.
References phpCAS::backtrace(), and phpCAS::log().
Referenced by CASClient::buildSAMLPayload(), CASClient::CASClient(), CASClient::checkAuthentication(), phpCAS::checkAuthentication(), phpCAS::client(), CASClient::forceAuthentication(), PGTStorageFile::getPGTIouFilename(), CASClient::getServerLoginURL(), CASClient::getServerSamlValidateURL(), CASClient::handleLogoutRequests(), PGTStorageFile::init(), CASClient::isAuthenticated(), phpCAS::logout(), phpCAS::logoutWithRedirectService(), phpCAS::logoutWithRedirectServiceAndUrl(), phpCAS::logoutWithUrl(), PGTStorage::PGTStorage(), PGTStorageDB::PGTStorageDB(), PGTStorageFile::PGTStorageFile(), phpCAS::proxy(), PGTStorageFile::read(), CASClient::readURL(), CASClient::renameSession(), CASClient::renewAuthentication(), CASClient::retrievePT(), phpCAS::serviceMail(), phpCAS::serviceWeb(), phpCAS::setCasServerCACert(), phpCAS::setCasServerCert(), phpCAS::setExtraCurlOption(), phpCAS::setFixedCallbackURL(), phpCAS::setFixedServiceURL(), phpCAS::setNoCasServerValidation(), phpCAS::setPGTStorageDB(), phpCAS::setPGTStorageFile(), phpCAS::setServerLoginURL(), phpCAS::setServerLogoutURL(), phpCAS::setServerProxyValidateURL(), phpCAS::setServerSamlValidateURL(), phpCAS::setServerServiceValidateURL(), CASClient::setSessionAttributes(), CASClient::wasPreviouslyAuthenticated(), and PGTStorageFile::write().
phpCAS::traceExit () [inherited]
This method is used to indicate the end of the execution of the program
Definition at line 617 of file CAS.php.
References phpCAS::log().
Referenced by CASClient::authError(), CASClient::callback(), phpCAS::error(), CASClient::handleLogoutRequests(), CASClient::logout(), and CASClient::redirectToCas().