phpCAS: Access to external services
Access to external services
[User interface]
Enumerations
enum PHPCAS_SERVICE_OK
enum PHPCAS_SERVICE_PT_NO_SERVER_RESPONSE
enum PHPCAS_SERVICE_PT_BAD_SERVER_RESPONSE
enum PHPCAS_SERVICE_PT_FAILURE
enum AVAILABLE
Functions
phpCAS::serviceWeb ($url, &$err_code, &$output)
phpCAS::serviceMail ($url, $service, $flags, &$err_code, &$err_msg, &$pt)
Enumeration Type Documentation
enum AVAILABLE
phpCAS::service() error code when the service was not available.
Definition at line 217 of file CAS.php.
enum PHPCAS_SERVICE_OK
phpCAS::service() error code on success
Definition at line 198 of file CAS.php.
enum PHPCAS_SERVICE_PT_BAD_SERVER_RESPONSE
phpCAS::service() error code when the PT could not retrieve because the response of the CAS server was ill-formed.
Definition at line 208 of file CAS.php.
enum PHPCAS_SERVICE_PT_FAILURE
phpCAS::service() error code when the PT could not retrieve because the CAS server did not want to.
Definition at line 213 of file CAS.php.
enum PHPCAS_SERVICE_PT_NO_SERVER_RESPONSE
phpCAS::service() error code when the PT could not retrieve because the CAS server did not respond.
Definition at line 203 of file CAS.php.
Function Documentation
phpCAS::serviceMail ($ url, $ service, $ flags, &$ err_code, &$ err_msg, &$ pt) [inherited]
This method is used to access an IMAP/POP3/NNTP service.
Parameters:
$url a string giving the URL of the service, including the mailing box for IMAP URLs, as accepted by imap_open().
$service a string giving for CAS retrieve Proxy ticket
$flags options given to imap_open().
$err_code an error code Possible values are PHPCAS_SERVICE_OK (on success), PHPCAS_SERVICE_PT_NO_SERVER_RESPONSE, PHPCAS_SERVICE_PT_BAD_SERVER_RESPONSE, PHPCAS_SERVICE_PT_FAILURE, PHPCAS_SERVICE_NOT AVAILABLE.
$err_msg an error message on failure
$pt the Proxy Ticket (PT) retrieved from the CAS server to access the URL on success, FALSE on error).
Returns:
an IMAP stream on success, FALSE otherwise (in this later case, $err_code gives the reason why it failed and $err_msg contains an error message).
Definition at line 871 of file CAS.php.
References $service, phpCAS::error(), phpCAS::traceBegin(), and phpCAS::traceEnd().
phpCAS::serviceWeb ($ url, &$ err_code, &$ output) [inherited]
This method is used to access an HTTP[S] service.
Parameters:
$url the service to access.
$err_code an error code Possible values are PHPCAS_SERVICE_OK (on success), PHPCAS_SERVICE_PT_NO_SERVER_RESPONSE, PHPCAS_SERVICE_PT_BAD_SERVER_RESPONSE, PHPCAS_SERVICE_PT_FAILURE, PHPCAS_SERVICE_NOT AVAILABLE.
$output the output of the service (also used to give an error message on failure).
Returns:
TRUE on success, FALSE otherwise (in this later case, $err_code gives the reason why it failed and $output contains an error message).
Examples:
example_proxy.php.
Definition at line 828 of file CAS.php.
References phpCAS::error(), phpCAS::traceBegin(), and phpCAS::traceEnd().