phpCAS: PGT storage on the filesystem
PGT storage on the filesystem
[PGT storage]
Classes
class PGTStorageFile
Functions
PGTStorageFile::getPath ()
PGTStorageFile::getFormat ()
PGTStorageFile::getStorageType ()
PGTStorageFile::getStorageInfo ()
PGTStorageFile::PGTStorageFile ($cas_parent, $format, $path)
PGTStorageFile::init ()
PGTStorageFile::getPGTIouFilename ($pgt_iou)
PGTStorageFile::write ($pgt, $pgt_iou)
PGTStorageFile::read ($pgt_iou)
Variables
PGTStorageFile::$_path
PGTStorageFile::$_format
Function Documentation
PGTStorageFile::getFormat () [private, inherited]
This method returns the format to use when storing PGT's on the filesystem.
Returns:
a string corresponding to the format used (plain or xml).
Definition at line 88 of file pgt-file.php.
Referenced by PGTStorageFile::getPGTIouFilename().
PGTStorageFile::getPath () [private, inherited]
This method returns the name of the directory where PGT's should be stored on the filesystem.
Returns:
the name of a directory (with leading and trailing '/')
Definition at line 68 of file pgt-file.php.
Referenced by PGTStorageFile::getPGTIouFilename().
PGTStorageFile::getPGTIouFilename ($ pgt_iou) [private, inherited]
This method returns the filename corresponding to a PGT Iou.
Parameters:
$pgt_iou the PGT iou.
Returns:
a filename
Definition at line 208 of file pgt-file.php.
References PGTStorageFile::getFormat(), PGTStorageFile::getPath(), phpCAS::traceBegin(), and phpCAS::traceEnd().
Referenced by PGTStorageFile::read(), and PGTStorageFile::write().
PGTStorageFile::getStorageInfo () [inherited]
This method returns an informational string giving informations on the parameters of the storage.(used for debugging purposes).
Returns:
an informational string.
Reimplemented from PGTStorage.
Definition at line 116 of file pgt-file.php.
PGTStorageFile::getStorageType () [inherited]
This method returns an informational string giving the type of storage used by the object (used for debugging purposes).
Returns:
an informational string.
Reimplemented from PGTStorage.
Definition at line 104 of file pgt-file.php.
PGTStorageFile::init () [inherited]
This method is used to initialize the storage. Halts on error.
Reimplemented from PGTStorage.
Definition at line 185 of file pgt-file.php.
References PGTStorage::isInitialized(), phpCAS::traceBegin(), and phpCAS::traceEnd().
PGTStorageFile::PGTStorageFile ($ cas_parent, $ format, $ path) [inherited]
The class constructor, called by CASClient::SetPGTStorageFile().
Parameters:
$cas_parent the CASClient instance that creates the object.
$format the format used to store the PGT's (`plain' and `xml' allowed).
$path the path where the PGT's should be stored
Definition at line 134 of file pgt-file.php.
References phpCAS::error(), PGTStorage::PGTStorage(), phpCAS::traceBegin(), and phpCAS::traceEnd().
PGTStorageFile::read ($ pgt_iou) [inherited]
This method reads a PGT corresponding to a PGT Iou and deletes the corresponding file.
Parameters:
$pgt_iou the PGT iou
Returns:
the corresponding PGT, or FALSE on error
Reimplemented from PGTStorage.
Definition at line 250 of file pgt-file.php.
References PGTStorageFile::getPGTIouFilename(), phpCAS::trace(), phpCAS::traceBegin(), and phpCAS::traceEnd().
PGTStorageFile::write ($ pgt, $ pgt_iou) [inherited]
This method stores a PGT and its corresponding PGT Iou into a file. Echoes a warning on error.
Parameters:
$pgt the PGT
$pgt_iou the PGT iou
Reimplemented from PGTStorage.
Definition at line 225 of file pgt-file.php.
References phpCAS::error(), PGTStorageFile::getPGTIouFilename(), phpCAS::traceBegin(), and phpCAS::traceEnd().
Variable Documentation
PGTStorageFile::$_format [private, inherited]
a string telling the format to use to store PGT's (plain or xml). Written by PGTStorageFile::PGTStorageFile(), read by getFormat().
Definition at line 79 of file pgt-file.php.
PGTStorageFile::$_path [private, inherited]
a string telling where PGT's should be stored on the filesystem. Written by PGTStorageFile::PGTStorageFile(), read by getPath().
Definition at line 58 of file pgt-file.php.