phpCAS: Authentication
Authentication
[User interface]
Functions
phpCAS::setCacheTimesForAuthRecheck ($n)
phpCAS::checkAuthentication ()
phpCAS::forceAuthentication ()
phpCAS::renewAuthentication ()
phpCAS::authenticate ()
phpCAS::isAuthenticated ()
phpCAS::isSessionAuthenticated ()
phpCAS::getUser ()
phpCAS::getAttributes ()
phpCAS::handleLogoutRequests ($check_client=true, $allowed_clients=false)
phpCAS::getServerLoginURL ()
phpCAS::setServerLoginURL ($url= '')
phpCAS::setServerServiceValidateURL ($url= '')
phpCAS::setServerProxyValidateURL ($url= '')
phpCAS::setServerSamlValidateURL ($url= '')
phpCAS::getServerLogoutURL ()
phpCAS::setServerLogoutURL ($url= '')
phpCAS::logout ($params="")
phpCAS::logoutWithRedirectService ($service)
phpCAS::logoutWithUrl ($url)
phpCAS::logoutWithRedirectServiceAndUrl ($service, $url)
phpCAS::setFixedCallbackURL ($url= '')
phpCAS::setFixedServiceURL ($url)
phpCAS::getServiceURL ()
phpCAS::retrievePT ($target_service, &$err_code, &$err_msg)
phpCAS::setCasServerCert ($cert)
phpCAS::setCasServerCACert ($cert)
phpCAS::setNoCasServerValidation ()
Function Documentation
phpCAS::authenticate () [inherited]
This method has been left from version 0.4.1 for compatibility reasons.
Definition at line 1020 of file CAS.php.
phpCAS::checkAuthentication () [inherited]
This method is called to check if the user is authenticated (use the gateway feature).
Returns:
TRUE when the user is authenticated; otherwise FALSE.
Examples:
example_gateway.php.
Definition at line 933 of file CAS.php.
References $auth, phpCAS::backtrace(), phpCAS::error(), phpCAS::traceBegin(), and phpCAS::traceEnd().
phpCAS::forceAuthentication () [inherited]
This method is called to force authentication if the user was not already authenticated. If the user is not authenticated, halt by redirecting to the CAS server.
Examples:
example_custom_urls.php, example_db.php, example_file.php, example_gateway.php, example_html.php, example_lang.php, example_proxy.php, example_proxy2.php, example_service.php, example_session_proxy.php, example_session_service.php, and example_simple.php.
Definition at line 961 of file CAS.php.
References $auth, phpCAS::backtrace(), phpCAS::error(), phpCAS::getUser(), phpCAS::trace(), and phpCAS::traceBegin().
phpCAS::getAttributes () [inherited]
This method returns the CAS user's login name.
Warning:
should not be called only after phpCAS::forceAuthentication() or phpCAS::checkAuthentication().
Returns:
the login name of the authenticated user
Definition at line 1096 of file CAS.php.
References phpCAS::error().
phpCAS::getServerLoginURL () [inherited]
This method returns the URL to be used to login. or phpCAS::isAuthenticated().
Returns:
the login name of the authenticated user
Definition at line 1126 of file CAS.php.
References phpCAS::error().
phpCAS::getServerLogoutURL () [inherited]
This method returns the URL to be used to login. or phpCAS::isAuthenticated().
Returns:
the login name of the authenticated user
Definition at line 1222 of file CAS.php.
References phpCAS::error().
phpCAS::getServiceURL () [inherited]
Get the URL that is set as the CAS service parameter.
Definition at line 1390 of file CAS.php.
References phpCAS::error().
phpCAS::getUser () [inherited]
This method returns the CAS user's login name.
Warning:
should not be called only after phpCAS::forceAuthentication() or phpCAS::checkAuthentication().
Returns:
the login name of the authenticated user
Examples:
example_lang.php.
Definition at line 1075 of file CAS.php.
References phpCAS::error().
Referenced by phpCAS::forceAuthentication().
phpCAS::handleLogoutRequests ($ check_client = true, $ allowed_clients = false) [inherited]
Handle logout requests.
Definition at line 1112 of file CAS.php.
References phpCAS::error().
phpCAS::isAuthenticated () [inherited]
This method is called to check if the user is authenticated (previously or by tickets given in the URL).
Returns:
TRUE when the user is authenticated.
Definition at line 1030 of file CAS.php.
phpCAS::isSessionAuthenticated () [inherited]
Checks whether authenticated based on $_SESSION. Useful to avoid server calls.
Returns:
true if authenticated, false otherwise.
Since:
0.4.22 by Brendan Arnold
Definition at line 1060 of file CAS.php.
phpCAS::logout ($ params = "") [inherited]
This method is used to logout from CAS. $params an array that contains the optional url and service parameters that will be passed to the CAS server
Examples:
example_custom_urls.php, example_gateway.php, and example_simple.php.
Definition at line 1255 of file CAS.php.
References phpCAS::error(), phpCAS::traceBegin(), and phpCAS::traceEnd().
phpCAS::logoutWithRedirectService ($ service) [inherited]
This method is used to logout from CAS. Halts by redirecting to the CAS server.
Parameters:
$service a URL that will be transmitted to the CAS server
Definition at line 1285 of file CAS.php.
References $service, phpCAS::error(), phpCAS::traceBegin(), and phpCAS::traceEnd().
phpCAS::logoutWithRedirectServiceAndUrl ($ service, $ url) [inherited]
This method is used to logout from CAS. Halts by redirecting to the CAS server.
Parameters:
$service a URL that will be transmitted to the CAS server
$url a URL that will be transmitted to the CAS server
Definition at line 1326 of file CAS.php.
References $service, phpCAS::error(), phpCAS::traceBegin(), and phpCAS::traceEnd().
phpCAS::logoutWithUrl ($ url) [inherited]
This method is used to logout from CAS. Halts by redirecting to the CAS server.
Parameters:
$url a URL that will be transmitted to the CAS server
Definition at line 1305 of file CAS.php.
References phpCAS::error(), phpCAS::traceBegin(), and phpCAS::traceEnd().
phpCAS::renewAuthentication () [inherited]
This method is called to renew the authentication.
Definition at line 995 of file CAS.php.
phpCAS::retrievePT ($ target_service, &$ err_code, &$ err_msg) [inherited]
Retrieve a Proxy Ticket from the CAS server.
Definition at line 1401 of file CAS.php.
References phpCAS::error().
phpCAS::setCacheTimesForAuthRecheck ($ n) [inherited]
Set the times authentication will be cached before really accessing the CAS server in gateway mode:
-1: check only once, and then never again (until you pree login)
0: always check
n: check every "n" time
Parameters:
$n an integer.
Definition at line 918 of file CAS.php.
References phpCAS::error().
phpCAS::setCasServerCACert ($ cert) [inherited]
Set the certificate of the CAS server CA.
Parameters:
$cert the CA certificate
Definition at line 1435 of file CAS.php.
References phpCAS::error(), phpCAS::traceBegin(), and phpCAS::traceEnd().
phpCAS::setCasServerCert ($ cert) [inherited]
Set the certificate of the CAS server.
Parameters:
$cert the PEM certificate
Definition at line 1417 of file CAS.php.
References phpCAS::error(), phpCAS::traceBegin(), and phpCAS::traceEnd().
phpCAS::setFixedCallbackURL ($ url = '') [inherited]
Set the fixed URL that will be used by the CAS server to transmit the PGT. When this method is not called, a phpCAS script uses its own URL for the callback.
Parameters:
$url the URL
Definition at line 1352 of file CAS.php.
References phpCAS::error(), phpCAS::traceBegin(), and phpCAS::traceEnd().
phpCAS::setFixedServiceURL ($ url) [inherited]
Set the fixed URL that will be set as the CAS service parameter. When this method is not called, a phpCAS script uses its own URL.
Parameters:
$url the URL
Definition at line 1374 of file CAS.php.
References phpCAS::error(), phpCAS::traceBegin(), and phpCAS::traceEnd().
phpCAS::setNoCasServerValidation () [inherited]
Set no SSL validation for the CAS server.
Examples:
example_custom_urls.php, example_db.php, example_file.php, example_gateway.php, example_html.php, example_lang.php, example_proxy.php, example_proxy2.php, example_service.php, example_session_proxy.php, example_session_service.php, and example_simple.php.
Definition at line 1451 of file CAS.php.
References phpCAS::error(), phpCAS::traceBegin(), and phpCAS::traceEnd().
phpCAS::setServerLoginURL ($ url = '') [inherited]
Set the login URL of the CAS server.
Parameters:
$url the login URL
Since:
0.4.21 by Wyman Chan
Definition at line 1139 of file CAS.php.
References phpCAS::error(), phpCAS::traceBegin(), and phpCAS::traceEnd().
phpCAS::setServerLogoutURL ($ url = '') [inherited]
Set the logout URL of the CAS server.
Parameters:
$url the logout URL
Since:
0.4.21 by Wyman Chan
Definition at line 1235 of file CAS.php.
References phpCAS::error(), phpCAS::traceBegin(), and phpCAS::traceEnd().
phpCAS::setServerProxyValidateURL ($ url = '') [inherited]
Set the proxyValidate URL of the CAS server. Used for all CAS 2.0 validations
Parameters:
$url the proxyValidate URL
Since:
1.1.0 by Joachim Fritschi
Examples:
example_custom_urls.php.
Definition at line 1181 of file CAS.php.
References phpCAS::error(), phpCAS::traceBegin(), and phpCAS::traceEnd().
phpCAS::setServerSamlValidateURL ($ url = '') [inherited]
Set the samlValidate URL of the CAS server.
Parameters:
$url the samlValidate URL
Since:
1.1.0 by Joachim Fritschi
Definition at line 1201 of file CAS.php.
References phpCAS::error(), phpCAS::traceBegin(), and phpCAS::traceEnd().
phpCAS::setServerServiceValidateURL ($ url = '') [inherited]
Set the serviceValidate URL of the CAS server. Used only in CAS 1.0 validations
Parameters:
$url the serviceValidate URL
Since:
1.1.0 by Joachim Fritschi
Definition at line 1160 of file CAS.php.
References phpCAS::error(), phpCAS::traceBegin(), and phpCAS::traceEnd().