phpCAS: HTML output
HTML output
[Configuration]
Functions
CASClient::HTMLFilterOutput ($str)
CASClient::printHTMLHeader ($title)
CASClient::printHTMLFooter ()
CASClient::setHTMLHeader ($header)
CASClient::setHTMLFooter ($footer)
Variables
CASClient::$_output_header
CASClient::$_output_footer
Function Documentation
CASClient::HTMLFilterOutput ($ str) [private, inherited]
This method filters a string by replacing special tokens by appropriate values and prints it. The corresponding tokens are taken into account:
__CAS_VERSION__
__PHPCAS_VERSION__
__SERVER_BASE_URL__
Used by CASClient::PrintHTMLHeader() and CASClient::printHTMLFooter().
Parameters:
$str the string to filter and output
Definition at line 81 of file client.php.
References CASClient::getServerBaseURL(), CASClient::getServerVersion(), and phpCAS::getVersion().
Referenced by CASClient::printHTMLFooter(), and CASClient::printHTMLHeader().
CASClient::printHTMLFooter () [private, inherited]
This method prints the footer of the HTML output (after filtering). If CASClient::setHTMLFooter() was not used, a default footer is output.
See also:
HTMLFilterOutput()
Definition at line 136 of file client.php.
References CASClient::getString(), and CASClient::HTMLFilterOutput().
Referenced by CASClient::logout(), and CASClient::redirectToCas().
CASClient::printHTMLHeader ($ title) [private, inherited]
This method prints the header of the HTML output (after filtering). If CASClient::setHTMLHeader() was not used, a default header is output.
Parameters:
$title the title of the page
See also:
HTMLFilterOutput()
Definition at line 108 of file client.php.
References CASClient::HTMLFilterOutput().
Referenced by CASClient::logout(), and CASClient::redirectToCas().
CASClient::setHTMLFooter ($ footer) [inherited]
This method set the HTML footer used for all outputs.
Parameters:
$footer the HTML footer.
Definition at line 162 of file client.php.
CASClient::setHTMLHeader ($ header) [inherited]
This method set the HTML header used for all outputs.
Parameters:
$header the HTML header.
Definition at line 150 of file client.php.
Variable Documentation
CASClient::$_output_footer [private, inherited]
A string used to print the footer of HTML pages. Written by CASClient::setHTMLFooter(), read by printHTMLFooter().
See also:
CASClient::setHTMLFooter, CASClient::printHTMLFooter()
Definition at line 127 of file client.php.
CASClient::$_output_header [private, inherited]
A string used to print the header of HTML pages. Written by CASClient::setHTMLHeader(), read by CASClient::printHTMLHeader().
See also:
CASClient::setHTMLHeader, CASClient::printHTMLHeader()
Definition at line 97 of file client.php.