phpCAS: PGT storage in a database
PGT storage in a database
[PGT storage]
Classes
class PGTStorageDB
Functions
PGTStorageDB::getURL ()
PGTStorageDB::getLink ()
PGTStorageDB::getTable ()
PGTStorageDB::getStorageType ()
PGTStorageDB::getStorageInfo ()
PGTStorageDB::PGTStorageDB ($cas_parent, $user, $password, $database_type, $hostname, $port, $database, $table)
PGTStorageDB::init ()
Variables
PGTStorageDB::$_url
PGTStorageDB::$_link
PGTStorageDB::$_table
Function Documentation
PGTStorageDB::getLink () [private, inherited]
This method returns the handle of the connection to the database where PGT's are stored.
Returns:
a handle of connection.
Definition at line 91 of file pgt-db.php.
PGTStorageDB::getStorageInfo () [inherited]
This method returns an informational string giving informations on the parameters of the storage.(used for debugging purposes).
Reimplemented from PGTStorage.
Definition at line 139 of file pgt-db.php.
PGTStorageDB::getStorageType () [inherited]
This method returns an informational string giving the type of storage used by the object (used for debugging purposes).
Returns:
an informational string.
Reimplemented from PGTStorage.
Definition at line 128 of file pgt-db.php.
PGTStorageDB::getTable () [private, inherited]
This method returns the name of the table where PGT's are stored.
Returns:
the name of a table.
Definition at line 112 of file pgt-db.php.
PGTStorageDB::getURL () [private, inherited]
This method returns the PEAR DB URL to use to connect to the database.
Returns:
a PEAR DB URL
Definition at line 69 of file pgt-db.php.
Referenced by PGTStorageDB::init().
PGTStorageDB::init () [inherited]
This method is used to initialize the storage. Halts on error.
Reimplemented from PGTStorage.
Definition at line 191 of file pgt-db.php.
References phpCAS::error(), PGTStorageDB::getURL(), PGTStorage::isInitialized(), and phpCAS::traceBegin().
PGTStorageDB::PGTStorageDB ($ cas_parent, $ user, $ password, $ database_type, $ hostname, $ port, $ database, $ table) [inherited]
The class constructor, called by CASClient::SetPGTStorageDB().
Parameters:
$cas_parent the CASClient instance that creates the object.
$user the user to access the data with
$password the user's password
$database_type the type of the database hosting the data
$hostname the server hosting the database
$port the port the server is listening on
$database the name of the database
$table the name of the table storing the data
Definition at line 162 of file pgt-db.php.
References PGTStorage::PGTStorage(), phpCAS::traceBegin(), and phpCAS::traceEnd().
Variable Documentation
PGTStorageDB::$_link [private, inherited]
The handle of the connection to the database where PGT's are stored. Written by PGTStorageDB::init(), read by getLink().
Definition at line 81 of file pgt-db.php.
PGTStorageDB::$_table [private, inherited]
The name of the table where PGT's are stored. Written by PGTStorageDB::PGTStorageDB(), read by getTable().
Definition at line 103 of file pgt-db.php.
PGTStorageDB::$_url [private, inherited]
a string representing a PEAR DB URL to connect to the database. Written by PGTStorageDB::PGTStorageDB(), read by getURL().
Definition at line 60 of file pgt-db.php.