phpCAS: PGT storage
PGT storage
[Configuration]
Enumerations
enum CAS_PGT_STORAGE_FILE_DEFAULT_PATH
enum CAS_PGT_STORAGE_FILE_FORMAT_PLAIN
enum CAS_PGT_STORAGE_FILE_FORMAT_XML
enum CAS_PGT_STORAGE_FILE_DEFAULT_FORMAT
enum CAS_PGT_STORAGE_DB_DEFAULT_DATABASE_TYPE
enum CAS_PGT_STORAGE_DB_DEFAULT_HOSTNAME
enum CAS_PGT_STORAGE_DB_DEFAULT_PORT
enum CAS_PGT_STORAGE_DB_DEFAULT_DATABASE
enum CAS_PGT_STORAGE_DB_DEFAULT_TABLE
Functions
phpCAS::setPGTStorageFile ($format= '', $path= '')
phpCAS::setPGTStorageDB ($user, $password, $database_type= '', $hostname= '', $port=0, $database= '', $table= '')
Enumeration Type Documentation
enum CAS_PGT_STORAGE_DB_DEFAULT_DATABASE
default database when storing PGT's to database
Definition at line 180 of file CAS.php.
enum CAS_PGT_STORAGE_DB_DEFAULT_DATABASE_TYPE
default database type when storing PGT's to database
Definition at line 168 of file CAS.php.
enum CAS_PGT_STORAGE_DB_DEFAULT_HOSTNAME
default host when storing PGT's to database
Definition at line 172 of file CAS.php.
enum CAS_PGT_STORAGE_DB_DEFAULT_PORT
default port when storing PGT's to database
Definition at line 176 of file CAS.php.
enum CAS_PGT_STORAGE_DB_DEFAULT_TABLE
default table when storing PGT's to database
Definition at line 184 of file CAS.php.
enum CAS_PGT_STORAGE_FILE_DEFAULT_FORMAT
Default format used when storing PGT's to file
Definition at line 161 of file CAS.php.
enum CAS_PGT_STORAGE_FILE_DEFAULT_PATH
Default path used when storing PGT's to file
Definition at line 149 of file CAS.php.
enum CAS_PGT_STORAGE_FILE_FORMAT_PLAIN
phpCAS::setPGTStorageFile()'s 2nd parameter to write plain text files
Definition at line 153 of file CAS.php.
enum CAS_PGT_STORAGE_FILE_FORMAT_XML
phpCAS::setPGTStorageFile()'s 2nd parameter to write xml files
Definition at line 157 of file CAS.php.
Function Documentation
phpCAS::setPGTStorageDB ($ user, $ password, $ database_type = '', $ hostname = '', $ port = 0, $ database = '', $ table = '') [inherited]
This method is used to tell phpCAS to store the response of the CAS server to PGT requests into a database.
Note:
The connection to the database is done only when needed. As a consequence, bad parameters are detected only when initializing PGT storage, except in debug mode.
Parameters:
$user the user to access the data with
$password the user's password
$database_type the type of the database hosting the data
$hostname the server hosting the database
$port the port the server is listening on
$database the name of the database
$table the name of the table storing the data
Examples:
example_db.php.
Definition at line 768 of file CAS.php.
References phpCAS::error(), phpCAS::traceBegin(), and phpCAS::traceEnd().
phpCAS::setPGTStorageFile ($ format = '', $ path = '') [inherited]
This method is used to tell phpCAS to store the response of the CAS server to PGT requests onto the filesystem.
Parameters:
$format the format used to store the PGT's (`plain' and `xml' allowed)
$path the path where the PGT's should be stored
Examples:
example_file.php.
Definition at line 730 of file CAS.php.
References phpCAS::error(), phpCAS::traceBegin(), and phpCAS::traceEnd().